---
# role: jomrr.nexus_oss
# file: tasks/main.yml

- name: "Install openjdk for Debian"
  ansible.builtin.package:
    name: "openjdk-{{ nexus_java_version }}-jdk"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: "Install openjdk for RedHat"
  ansible.builtin.package:
    name: "java-{{ nexus_java_version }}-openjdk"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Create nexus group"
  ansible.builtin.group:
    name: "{{ nexus_group }}"
    state: present

- name: "Create nexus user"
  ansible.builtin.user:
    name: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    home: "{{ nexus_home }}"
    shell: "/bin/bash"
    system: true
    state: present

- name: "Ensure directories with correct permissions"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    mode: '0750'
  loop:
    - "{{ nexus_home }}"
    - "{{ nexus_data }}"
    - "{{ nexus_data }}/etc"

- name: "Download Nexus OSS"
  ansible.builtin.get_url:
    url: "{{ nexus_download_url }}"
    dest: "/tmp/nexus.tar.gz"
    mode: "0644"
  environment:
    http_proxy: "{{ nexus_http_proxy | default(omit) }}"
    https_proxy: "{{ nexus_https_proxy | default(omit) }}"
  register: nexus_download

- name: "Extract Nexus OSS"
  ansible.builtin.unarchive:
    src: "/tmp/nexus.tar.gz"
    dest: "{{ nexus_home }}"
    remote_src: true
    extra_opts: [--strip-components=1]
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"

- name: "Create and enable systemd unit file"
  ansible.builtin.template:
    src: "nexus-oss.service.j2"
    dest: "/etc/systemd/system/nexus-oss.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Reload systemd"

- name: "Generate nexus configuration files"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nexus_user }}"
    group: "{{ nexus_group }}"
    mode: "0640"
  notify: "Restart nexus-oss"
  loop:
    - { src: "nexus.properties.j2", dest: "{{ nexus_data }}/etc/nexus.properties" }
    - { src: "nexus.rc.j2", dest: "{{ nexus_home }}/bin/nexus.rc" }
    - { src: "nexus.vmoptions.j2", dest: "{{ nexus_home }}/bin/nexus.vmoptions" }
