---
# role: jomrr.nexus_oss
# file: handlers/main.yml

- name: "Reload systemd and enable nexus-oss"
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    state: restarted
    name: nexus-oss
