---
# role: jomrr.nexus_oss
# file: handlers/main.yml

- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Restart nexus-oss"
  ansible.builtin.systemd:
    name: "nexus-oss"
    state: restarted
    enabled: true
