# role: jomrr.nexus_oss
# file: molecule/resources/playbooks/verify.yml

- name: "PLAYBOOK | Verify | nexus_oss"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Assert true"
      ansible.builtin.assert:
        that: "true"
        fail_msg: "This should never fail"
